### ISSUE TITLE
PG::UndefinedFunction: ERROR:  operator does not exist: bigint = uuid

### ISSUE THREAD

**Issue by awesome** [jonhue/acts_as_favoritor#225]
**Describe the bug**

```
PG::UndefinedFunction: ERROR:  operator does not exist: bigint = uuid
LINE 1: ...table_type" = $1 AND "favorites"."favoritable_id" = "partner...

```

**To Reproduce**

Use Postgres `uuid` plugin for `id`.

Default generator output:
```
create_table "favorites", force: :cascade do |t|
  t.string "favoritable_type", null: false
  t.bigint  "favoritable_id", null: false
  t.string "favoritor_type", null: false
  t.bigint  "favoritor_id", null: false
  t.string "scope", default: "favorite", null: false
[…]
end

```

** Fix **

After generating migration, before `rails db:migrate`, append `t.references…` lines with `type: :uuid` 

```
create_table :favorites, force: true do |t|
  t.references :favoritable, polymorphic: true, null: false, type: :uuid
  t.references :favoritor, polymorphic: true, null: false, type: :uuid


```

**Expected behavior**

```
create_table "favorites", force: :cascade do |t|
  t.string "favoritable_type", null: false
  t.uuid "favoritable_id", null: false
  t.string "favoritor_type", null: false
  t.uuid "favoritor_id", null: false
  t.string "scope", default: "favorite", null: false
[…]
end

```

**Environment**

Rails 6

**Comment by jonhue** [comment]
Is this a bug? When using the uuid plugin, you can just change the generator output.

**Comment by awesome** [comment]
Not really a bug, but a solution for using acts_as_favoritor with Postgres UUID extension. Didn't work OTB, so found a solution and recording it here. Zero search results for uuid in the repo: https://github.com/jonhue/acts_as_favoritor/search?q=uuid

Thanks for the tip "you can just change the generator output." Sounds great, but still don't know how to do that.
