### ISSUE TITLE
Mysql2::Error: Specified key was too long; max key length is 3072 bytes

### ISSUE THREAD

**Issue by estebanutz** [jonhue/acts_as_favoritor#237]
I'm getting this error when trying to run the migration:
**Mysql2::Error: Specified key was too long; max key length is 3072 bytes**

I'm running Rails 6.1.4.1, MySQL 8.0.26. The adapter is mysql2 and encoding utf8mb4. Any ideas on how to fix this issue? I looked quite bit online and tried several "solutions" without any luck. I can provide more information if needed. Thanks!

**Comment by jonhue** [comment]
I haven't encountered this myself. A good strategy might be to apply the migration changes one by one and see which exact step fails.
