### ISSUE TITLE
Issue with scope string

### ISSUE THREAD

**Issue by mhdrahmoun** [jonhue/acts_as_favoritor#26]
Hi there,
I'm trying to use this gem in my project and I noticed a strange behavior in the `Favoritor` methods.
I could `favorite` a favoritable item successfully but I couldn't get the `favorites_count`, `remove_favorite` or `favorited?` results.
after some checking, I found that the scope string is saved "favorite" in the database but when trying to select from the Favorite table you pass the string "Favorite" which means you'll get 0 results as the strings are not identical.

Thank you.

**Comment by jonhue** [comment]
I looked into this and cannot see a case in which this gem would select `Favorite`s instead of `favorite`s. Perhaps I am just missing your point though. Please provide some information for me to reproduce and I will be happy to reopen this ticket.

**Comment by jonhue** [comment]
Unless you are explicitly setting the scope to `Favorite`, this gem will neither use it to store nor to retrieve favorites.

**Comment by mhdrahmoun** [comment]
No, I'm not setting the scope to `Favorite`

**Comment by mhdrahmoun** [comment]
Okay..
I did some testing using rails console with the following cases:
1- using the gem from this repository
when running `user.favorite book`
I got` Favorite Load (0.4ms)  SELECT  "favorites".* FROM "favorites" WHERE "favorites"."favoritor_id" = $1 AND "favorites"."favoritor_type" = $2 AND "favorites"."favoritable_id" = $3 AND "favorites"."favoritable_type" = $4 AND "favorites"."scope" = $5 ORDER BY "favorites"."id" ASC LIMIT $6  [["favoritor_id", 21], ["favoritor_type", "User"], ["favoritable_id", 7], ["favoritable_type", "Book"], ["scope", "favorite"], ["LIMIT", 1]]`
then it will do the INSERT operation.

now, when trying to  `remove_favorite` I got:
`Favorite Load (0.8ms)  SELECT  "favorites".* FROM "favorites" WHERE "favorites"."favoritor_id" = $1 AND "favorites"."favoritor_type" = $2 AND "favorites"."blocked" = $3 AND "favorites"."scope" = $4 AND "favorites"."favoritable_id" = $5 AND "favorites"."favoritable_type" = $6 ORDER BY "favorites"."id" ASC LIMIT $7  [["favoritor_id", 21], ["favoritor_type", "User"], ["blocked", false], ["scope", "Favorite"], ["favoritable_id", 7], ["favoritable_type", "Book"], ["LIMIT", 1]]`
and it returns `nil` as it didn't find the record to delete.

2- when changing default scope to be `Favorite` instead of `favorite` everything is working perfectly.

**Comment by djaircarvalho** [comment]
What SGBD are you using?

**Comment by djaircarvalho** [comment]
@mhdrahmoun this issue was already solved in master. I suggest you use `gem 'acts_as_favoritor', github: 'jonhue/acts_as_favoritor'`  in your Gemfile until @jonhue update the gem in rubygems.org

**Comment by jonhue** [comment]
Good point @djaircarvalho. Will do so.
