### ISSUE TITLE
Add magic methods for scopes

### ISSUE THREAD

**Issue by jonhue** [jonhue/acts_as_favoritor#3]
`user.follow(second_user)` instead of `user.favorite(second_user, scope: [:follow])`

**Comment by synth** [comment]
Hello! We're discovering this gem as we soon want to build the ability to add "Reactions" which are emojis that are tagged to any object like posts or comments similiar to Slack and Github. Indeed, it would be nice to have a semantic dsl for "Reactions". Something like: 

```
user.react_to(post, with: :thumbs_up)
user.react_to(comment, with: 😓 )
```

We might be able to contribute to this gem depending on if there is interest and what the scope of work is. Let me know if you think this is worthwhile to add and if we can collaborate on the specification for such. 

Thanks!

**Comment by jonhue** [comment]
Hey, thank you for your proposal! I don't think I fully understand what change you're seeking. From my pov your use case is already covered by 

```
user.favorite(post, scopes: [:reaction_thumbs_up])
```

All that `react_to` would be is a slightly different interface for the same behavior. If you prefer that interface, you can easily build that with a couple of lines of code (it's really just renaming the function and its parameters essentially). Am I missing anything? 🙂

**Comment by jonhue** [comment]
On another note, I'm not too on board with this magic methods change anymore. IMO it is best to have a unified and flexible API. Happy to be convinced of the contrary and read through proposals of how this could be implemented though.

**Comment by synth** [comment]
Thanks for getting back. Yea, I suppose it's just a wrapper. I could also imagine view helpers to really create a nice abstraction so reactions are first class and super easy to integrate into an app. Although, I don't know if you want any view layer code in this gem.

**Comment by jonhue** [comment]
yeah, I think keeping this separate from the model would be a good design choice imo.

Regarding the caching, as mentioned in the readme scores are stored in the database, so it should be a single query for a single item.
