### ISSUE TITLE
`#favorited?` does not work

### ISSUE THREAD

**Issue by RudyOnRails** [jonhue/acts_as_favoritor#32]
**Describe the bug**
[This](https://github.com/jonhue/acts_as_favoritor/blob/master/lib/acts_as_favoritor/favoritor.rb#L24) method returns false when it really is true.

https://github.com/jonhue/acts_as_favoritor/blob/fe2c648ba1e7c2bae1fa631b9ac7d2df98dcb4f1/lib/acts_as_favoritor/favoritor.rb#L22-L41

**To Reproduce**
1. Setup as normal and use the method
showterm example: http://showterm.io/7e6c76d697f66da491df5#

**Expected behavior**
Should return true if the favoritor has favorited the favoritable object.

**Additional context**
If you swap the logic out with acts_as_follower's code at https://github.com/tcocca/acts_as_follower/blob/master/lib/acts_as_follower/follower.rb#L20 and reboot your server, it returns true as expected.
```
def favorited?(favoritable)
    0 < Favorite.unblocked.for_favoritor(self).for_favoritable(favoritable).count
end
```

**Comment by jonhue** [comment]
@RudyOnRails Could you try passing the scope explicitly? `user.favorited?(artist, scope: 'favorite')`?

**Comment by RudyOnRails** [comment]
Hi Jonas, sorry I haven't gotten back to you. I needed to get the feature
done for work, so that day I reported the problem I switched back to the
original acts_as_follower gem and just PR'ed the original migration
generator problem they were having that made me give yours a try.

Best,
Kevin

>

**Comment by jonhue** [comment]
@RudyOnRails I suspect, this failed cause some weird setting for the default favorite scope. It appears that your `Favorite` record was of the default type `favorite`. But judging from the generated SQL query for `user.favorited?(artist)` your configuration of the default scope changed from `favorite` to `Favorite`.

This functionality is actually pretty well tested, so my guess is that this was a configuration problem.
