### ISSUE TITLE
Undefined method '+' for :scope:Symbol

### ISSUE THREAD

**Issue by bctoh** [jonhue/acts_as_favoritor#35]
**Walkthrough**
Awesome gem so far, enjoyed using it to implement a `favorite` functionality which works great. Right now, I'd like to add a scope for `verify` functionality. Adding the scope to `verify` works but when I check if it's been favorited with `verify` scope or try to `remove_favorite` with the verify scope, I get the following error:

`NoMethodError: undefined method `+' for :verify:Symbol`

Any ideas?

I saw #26 and tried to use this `gem 'acts_as_favoritor', github: 'jonhue/acts_as_favoritor'` in the gemfile instead to get the latest version but niet.

**Screenshot**
See attached 👇 

<img width="1106" alt="screenshot 2019-03-08 at 4 40 02 pm" src="https://user-images.githubusercontent.com/9085849/54017593-73466e80-41c1-11e9-8c98-fe8dbf3d92d5.png">

**Expected behavior**
Expected behaviour was to receive a `true` or `false` if user has been verified and to be able to remove verification.

**Local env:**
 - OS: MacOS Mojave 10.14.3
 - Browser: Chrome
 - Version 72.0.3626.119

**Comment by bctoh** [comment]
The issue seems to be coming from here https://github.com/jonhue/acts_as_favoritor/blob/master/lib/acts_as_favoritor/favoritor.rb#L38-L39

**Comment by jonhue** [comment]
I'll be looking into it. Thanks for the report!

**Comment by bctoh** [comment]
Awesome man, it works! 🎉 Thx so much for the prompt fix 🙏  @jonhue 

> I'll be looking into it. Thanks for the report!
