### ISSUE TITLE
Undefined local variable or method `favoritable' when using caching

### ISSUE THREAD

**Issue by kwent** [jonhue/acts_as_favoritor#77]
```ruby
[10] pry(main)> ActsAsFavoritor::VERSION
=> "4.0.0"
[11] pry(main)> ActsAsFavoritor.configuration.default_scope
=> :favorite
[12] pry(main)> ActsAsFavoritor.configuration.cache
=> true
[13] pry(main)> User.last.favorite Product.last
NameError: undefined local variable or method `favoritable' for #<User:0x00007ff366a70b00>
from /Users/foo/.rbenv/versions/2.6.1/lib/ruby/gems/2.6.0/gems/activemodel-5.2.3/lib/active_model/attribute_methods.rb:430:in `method_missing'
```

**Comment by jonhue** [comment]
Where do the docs say that `favoritable` is available as an instance method?

**Comment by kwent** [comment]
Hi @jonhue , not sure i follow but my `User` class have `acts_as_favoritor` and my `Product` class have `acts_as_favoritable`.

**Comment by kwent** [comment]
I actually think there is another bug with caching here https://github.com/jonhue/acts_as_favoritor/blob/master/lib/acts_as_favoritor/favoritor.rb#L132 where `favoritable` is `undefined`

**Comment by jonhue** [comment]
`favoritable` is an association on the `Favorite` class. So you wont be able to access it on instances of either of your classes directly.

**Comment by jonhue** [comment]
If you want to get the products a user favorited, use  `User.last.favorited_products`

**Comment by jonhue** [comment]
Your right about the bug though. This should be `self` instead. Sadly, I haven't gotten to write tests for caching yet.

**Comment by kwent** [comment]
All good ! I'll monkeypatch my side in the meantime :)
