### ISSUE TITLE
favorited_by_type and return type

### ISSUE THREAD

**Issue by kwent** [jonhue/acts_as_favoritor#79]
Hi, 

So in 2.1.2 `favorited_by_type` used to return an active record relationship object and we could do stuff like `User.favorited_by_type('Product', scopes: [:foo]).not_deleted.enabled`. How do we do this now ?

Now it's returning an array and i didn't see this in the breaking changes changelog AFAIK

Also README says you can pass `:limit` and `:order` parameters https://github.com/jonhue/acts_as_favoritor#acts_as_favoritor-methods, but i think that got killed as well.

I filled this as a bug but might a documentation update depending your intentions.

**Comment by jonhue** [comment]
This should be an active record relationship object. Good catch! I removed the `limit` and `order` options as they are unnecessary then.
