### ISSUE TITLE
Validation failed: Favoritor must exist

### ISSUE THREAD

**Issue by andreimerfu** [jonhue/acts_as_favoritor#87]
![Screenshot from 2019-05-18 10-31-23](https://user-images.githubusercontent.com/12085472/57966273-37195200-7958-11e9-83b3-ea70f653ec2a.png)

Hello. I have this problem and I do not know how to fix it. In the past, it worked smoothly but now something has happened.
In the Profile model, I have acts_as_favoritor and in the Job model, I have acts_as_favoritable. Both current_profile and job is not nil or something.

Thanks

**Comment by jonhue** [comment]
Are you sure that `current_profile` is persisted? Because the exception indicates it is not.

**Comment by andreimerfu** [comment]
![Screenshot from 2019-05-18 11-20-43](https://user-images.githubusercontent.com/12085472/57966769-01c43280-795f-11e9-8dec-baaf27b1fa88.png)
Yes, is persisted.

**Comment by jonhue** [comment]
Have you used another major version of this gem previously? (< 3.0.0)

**Comment by andreimerfu** [comment]
Yes, I used 2.1.1

**Comment by jonhue** [comment]
I think this method is rather well tested (for example [here](https://github.com/jonhue/acts_as_favoritor/blob/master/spec/lib/acts_as_favoritor/favoritor_spec.rb#L26)). I'm afraid, I can't provide any further assistance unless you provide a reproduceable example.

**Comment by jonhue** [comment]
@andreimerfu did you find the problem?
