### ISSUE TITLE
scope capitalized within #favorited_by? and # favorited? 

### ISSUE THREAD

**Issue by RonWalker22** [jonhue/acts_as_favoritor#98]
**Describe the bug**

#favorited_by? and #favorited? are not working for me. I believe it is because the scope is being capitalized somewhere within #favorited_by? and # favorited?.
I'm using the default scope. If I change the default scope to anything else, it also gets capitalized. When I change the default scope to a capitalized word, the methods work as expected.

**Screenshots**

![fav-scope-bug](https://user-images.githubusercontent.com/18250094/63613454-af199880-c595-11e9-8d7a-5a70cffd4f3b.png)

**Additional context**
This might be related to #32

**Comment by RonWalker22** [comment]
Sorry I was using an old gem version. This issue has already been fixed. 

@jonhue Why does `gem 'acts_as_favoritor'` points to version 2.0.1?

**Comment by jonhue** [comment]
If you have a lockfile that uses 2.0.1 you have to explicitly update the gem or change the gemfile to reference the desired version.
